// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/openrasp_cloud.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/openrasp_cloud.proto

It has these top-level messages:
	UpdateInfo
	Agent
	Rasp
	UpdateResult
	RegistrationResponse
	AddRaspResponse
	SumData
	HeartBeatInfo
	Plugin
	PropertiesConf
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// 升级信息
type UpdateInfo struct {
	Id             string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RaspId         []string        `protobuf:"bytes,5,rep,name=raspId" json:"raspId,omitempty"`
	PropertiesConf *PropertiesConf `protobuf:"bytes,2,opt,name=propertiesConf" json:"propertiesConf,omitempty"`
	Plugins        []*Plugin       `protobuf:"bytes,4,rep,name=plugins" json:"plugins,omitempty"`
}

func (m *UpdateInfo) Reset()                    { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string            { return proto1.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()               {}
func (*UpdateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateInfo) GetRaspId() []string {
	if m != nil {
		return m.RaspId
	}
	return nil
}

func (m *UpdateInfo) GetPropertiesConf() *PropertiesConf {
	if m != nil {
		return m.PropertiesConf
	}
	return nil
}

func (m *UpdateInfo) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

// Agent信息
type Agent struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	HostName string `protobuf:"bytes,6,opt,name=hostName" json:"hostName,omitempty"`
	Os       string `protobuf:"bytes,8,opt,name=os" json:"os,omitempty"`
	Version  string `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
}

func (m *Agent) Reset()                    { *m = Agent{} }
func (m *Agent) String() string            { return proto1.CompactTextString(m) }
func (*Agent) ProtoMessage()               {}
func (*Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Agent) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Agent) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// rasp 信息
type Rasp struct {
	Id              string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type            string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	Version         string `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
	LanguageVersion string `protobuf:"bytes,7,opt,name=languageVersion" json:"languageVersion,omitempty"`
	RaspHome        string `protobuf:"bytes,8,opt,name=raspHome" json:"raspHome,omitempty"`
	StartTime       uint64 `protobuf:"varint,9,opt,name=startTime" json:"startTime,omitempty"`
}

func (m *Rasp) Reset()                    { *m = Rasp{} }
func (m *Rasp) String() string            { return proto1.CompactTextString(m) }
func (*Rasp) ProtoMessage()               {}
func (*Rasp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rasp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Rasp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Rasp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Rasp) GetLanguageVersion() string {
	if m != nil {
		return m.LanguageVersion
	}
	return ""
}

func (m *Rasp) GetRaspHome() string {
	if m != nil {
		return m.RaspHome
	}
	return ""
}

func (m *Rasp) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

// update 结果
type UpdateResult struct {
	UpdateId  string `protobuf:"bytes,1,opt,name=updateId" json:"updateId,omitempty"`
	IsSuccess bool   `protobuf:"varint,2,opt,name=isSuccess" json:"isSuccess,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateResult) Reset()                    { *m = UpdateResult{} }
func (m *UpdateResult) String() string            { return proto1.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()               {}
func (*UpdateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateResult) GetUpdateId() string {
	if m != nil {
		return m.UpdateId
	}
	return ""
}

func (m *UpdateResult) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *UpdateResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Agent注册返回信息
type RegistrationResponse struct {
	IsSuccess bool   `protobuf:"varint,1,opt,name=isSuccess" json:"isSuccess,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RegistrationResponse) Reset()                    { *m = RegistrationResponse{} }
func (m *RegistrationResponse) String() string            { return proto1.CompactTextString(m) }
func (*RegistrationResponse) ProtoMessage()               {}
func (*RegistrationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegistrationResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *RegistrationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 添加Rasp的返回信息
type AddRaspResponse struct {
	IsSuccess bool `protobuf:"varint,1,opt,name=isSuccess" json:"isSuccess,omitempty"`
	// 添加失败的话 失败信息
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *AddRaspResponse) Reset()                    { *m = AddRaspResponse{} }
func (m *AddRaspResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddRaspResponse) ProtoMessage()               {}
func (*AddRaspResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddRaspResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *AddRaspResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 统计信息
type SumData struct {
	Block   map[string]int64 `protobuf:"bytes,1,rep,name=block" json:"block,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Info    map[string]int64 `protobuf:"bytes,2,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Hook    map[string]int64 `protobuf:"bytes,3,rep,name=hook" json:"hook,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Request int64            `protobuf:"varint,4,opt,name=request" json:"request,omitempty"`
}

func (m *SumData) Reset()                    { *m = SumData{} }
func (m *SumData) String() string            { return proto1.CompactTextString(m) }
func (*SumData) ProtoMessage()               {}
func (*SumData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SumData) GetBlock() map[string]int64 {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SumData) GetInfo() map[string]int64 {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SumData) GetHook() map[string]int64 {
	if m != nil {
		return m.Hook
	}
	return nil
}

func (m *SumData) GetRequest() int64 {
	if m != nil {
		return m.Request
	}
	return 0
}

// 心跳信息
type HeartBeatInfo struct {
	Id           string              `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	SumData      map[string]*SumData `protobuf:"bytes,1,rep,name=sumData" json:"sumData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdateResult *UpdateResult       `protobuf:"bytes,2,opt,name=updateResult" json:"updateResult,omitempty"`
}

func (m *HeartBeatInfo) Reset()                    { *m = HeartBeatInfo{} }
func (m *HeartBeatInfo) String() string            { return proto1.CompactTextString(m) }
func (*HeartBeatInfo) ProtoMessage()               {}
func (*HeartBeatInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *HeartBeatInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HeartBeatInfo) GetSumData() map[string]*SumData {
	if m != nil {
		return m.SumData
	}
	return nil
}

func (m *HeartBeatInfo) GetUpdateResult() *UpdateResult {
	if m != nil {
		return m.UpdateResult
	}
	return nil
}

// js插件
type Plugin struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Plugin) Reset()                    { *m = Plugin{} }
func (m *Plugin) String() string            { return proto1.CompactTextString(m) }
func (*Plugin) ProtoMessage()               {}
func (*Plugin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// properties 配置
type PropertiesConf struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *PropertiesConf) Reset()                    { *m = PropertiesConf{} }
func (m *PropertiesConf) String() string            { return proto1.CompactTextString(m) }
func (*PropertiesConf) ProtoMessage()               {}
func (*PropertiesConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PropertiesConf) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto1.RegisterType((*UpdateInfo)(nil), "proto.UpdateInfo")
	proto1.RegisterType((*Agent)(nil), "proto.Agent")
	proto1.RegisterType((*Rasp)(nil), "proto.Rasp")
	proto1.RegisterType((*UpdateResult)(nil), "proto.UpdateResult")
	proto1.RegisterType((*RegistrationResponse)(nil), "proto.RegistrationResponse")
	proto1.RegisterType((*AddRaspResponse)(nil), "proto.AddRaspResponse")
	proto1.RegisterType((*SumData)(nil), "proto.SumData")
	proto1.RegisterType((*HeartBeatInfo)(nil), "proto.HeartBeatInfo")
	proto1.RegisterType((*Plugin)(nil), "proto.Plugin")
	proto1.RegisterType((*PropertiesConf)(nil), "proto.PropertiesConf")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OpenRASP service

type OpenRASPClient interface {
	// 心跳请求
	HeartBeat(ctx context.Context, opts ...grpc.CallOption) (OpenRASP_HeartBeatClient, error)
	// 注册agent
	Register(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// 添加 Rasp
	AddRasp(ctx context.Context, in *Rasp, opts ...grpc.CallOption) (*AddRaspResponse, error)
}

type openRASPClient struct {
	cc *grpc.ClientConn
}

func NewOpenRASPClient(cc *grpc.ClientConn) OpenRASPClient {
	return &openRASPClient{cc}
}

func (c *openRASPClient) HeartBeat(ctx context.Context, opts ...grpc.CallOption) (OpenRASP_HeartBeatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_OpenRASP_serviceDesc.Streams[0], c.cc, "/proto.OpenRASP/HeartBeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &openRASPHeartBeatClient{stream}
	return x, nil
}

type OpenRASP_HeartBeatClient interface {
	Send(*HeartBeatInfo) error
	Recv() (*UpdateInfo, error)
	grpc.ClientStream
}

type openRASPHeartBeatClient struct {
	grpc.ClientStream
}

func (x *openRASPHeartBeatClient) Send(m *HeartBeatInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *openRASPHeartBeatClient) Recv() (*UpdateInfo, error) {
	m := new(UpdateInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *openRASPClient) Register(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := grpc.Invoke(ctx, "/proto.OpenRASP/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openRASPClient) AddRasp(ctx context.Context, in *Rasp, opts ...grpc.CallOption) (*AddRaspResponse, error) {
	out := new(AddRaspResponse)
	err := grpc.Invoke(ctx, "/proto.OpenRASP/AddRasp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OpenRASP service

type OpenRASPServer interface {
	// 心跳请求
	HeartBeat(OpenRASP_HeartBeatServer) error
	// 注册agent
	Register(context.Context, *Agent) (*RegistrationResponse, error)
	// 添加 Rasp
	AddRasp(context.Context, *Rasp) (*AddRaspResponse, error)
}

func RegisterOpenRASPServer(s *grpc.Server, srv OpenRASPServer) {
	s.RegisterService(&_OpenRASP_serviceDesc, srv)
}

func _OpenRASP_HeartBeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OpenRASPServer).HeartBeat(&openRASPHeartBeatServer{stream})
}

type OpenRASP_HeartBeatServer interface {
	Send(*UpdateInfo) error
	Recv() (*HeartBeatInfo, error)
	grpc.ServerStream
}

type openRASPHeartBeatServer struct {
	grpc.ServerStream
}

func (x *openRASPHeartBeatServer) Send(m *UpdateInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *openRASPHeartBeatServer) Recv() (*HeartBeatInfo, error) {
	m := new(HeartBeatInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _OpenRASP_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenRASPServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OpenRASP/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenRASPServer).Register(ctx, req.(*Agent))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenRASP_AddRasp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rasp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenRASPServer).AddRasp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OpenRASP/AddRasp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenRASPServer).AddRasp(ctx, req.(*Rasp))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenRASP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OpenRASP",
	HandlerType: (*OpenRASPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _OpenRASP_Register_Handler,
		},
		{
			MethodName: "AddRasp",
			Handler:    _OpenRASP_AddRasp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartBeat",
			Handler:       _OpenRASP_HeartBeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/openrasp_cloud.proto",
}

func init() { proto1.RegisterFile("proto/openrasp_cloud.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xae, 0x37, 0xfb, 0x3b, 0xbb, 0xdd, 0x82, 0x29, 0x95, 0x09, 0x1c, 0x96, 0x08, 0x89, 0x08,
	0xa1, 0xb6, 0x5a, 0x24, 0x5a, 0x15, 0x71, 0x68, 0x01, 0xa9, 0xe5, 0x50, 0x2a, 0x17, 0xb8, 0x22,
	0x77, 0xe3, 0x6e, 0xa3, 0xee, 0xda, 0x21, 0x76, 0x2a, 0xf5, 0x5d, 0x78, 0x00, 0xae, 0xbc, 0x0f,
	0x17, 0xde, 0x04, 0xd9, 0x4e, 0xb2, 0x49, 0xbb, 0x42, 0xaa, 0x38, 0x25, 0x33, 0xfe, 0xe6, 0xf3,
	0xcc, 0xe7, 0x99, 0x01, 0x3f, 0x49, 0xa5, 0x96, 0x5b, 0x32, 0xe1, 0x22, 0x65, 0x2a, 0xf9, 0x36,
	0x99, 0xc9, 0x2c, 0xda, 0xb4, 0x4e, 0xdc, 0xb2, 0x9f, 0xe0, 0x07, 0x02, 0xf8, 0x92, 0x44, 0x4c,
	0xf3, 0x23, 0x71, 0x2e, 0xf1, 0x10, 0x1a, 0x71, 0x44, 0xd0, 0x08, 0x85, 0x3d, 0xda, 0x88, 0x23,
	0xbc, 0x01, 0x6d, 0x13, 0x79, 0x14, 0x91, 0xd6, 0xc8, 0x0b, 0x7b, 0x34, 0xb7, 0xf0, 0x5b, 0x18,
	0x26, 0xa9, 0x4c, 0x78, 0xaa, 0x63, 0xae, 0xde, 0x49, 0x71, 0x4e, 0x1a, 0x23, 0x14, 0xf6, 0xc7,
	0x0f, 0x1d, 0xfb, 0xe6, 0x49, 0xed, 0x90, 0xde, 0x00, 0xe3, 0xe7, 0xd0, 0x49, 0x66, 0xd9, 0x34,
	0x16, 0x8a, 0x34, 0x47, 0x5e, 0xd8, 0x1f, 0xaf, 0x16, 0x71, 0xd6, 0x4b, 0x8b, 0xd3, 0x40, 0x42,
	0x6b, 0x7f, 0xca, 0x85, 0xbe, 0x95, 0xd8, 0x3d, 0xf0, 0x2e, 0xf9, 0xb5, 0xbd, 0xb5, 0x47, 0xcd,
	0x2f, 0xf6, 0xa1, 0x7b, 0x21, 0x95, 0x3e, 0x66, 0x73, 0x4e, 0xda, 0xd6, 0x5d, 0xda, 0x26, 0x5a,
	0x2a, 0xd2, 0x75, 0xd1, 0x52, 0x61, 0x02, 0x9d, 0x2b, 0x9e, 0xaa, 0x58, 0x0a, 0xd2, 0xb1, 0xce,
	0xc2, 0x0c, 0x7e, 0x22, 0x68, 0x52, 0xa6, 0x92, 0x5b, 0x17, 0x62, 0x68, 0xea, 0xeb, 0x84, 0x93,
	0x96, 0xf5, 0xd8, 0xff, 0x2a, 0x4d, 0xbb, 0x46, 0x83, 0x43, 0x58, 0x9b, 0x31, 0x31, 0xcd, 0xd8,
	0x94, 0x7f, 0xad, 0x5d, 0x74, 0xd3, 0x6d, 0xd2, 0x36, 0x9a, 0x1e, 0xca, 0x39, 0xcf, 0x13, 0x2c,
	0x6d, 0xfc, 0x04, 0x7a, 0x4a, 0xb3, 0x54, 0x7f, 0x8e, 0xe7, 0x9c, 0xf4, 0x46, 0x28, 0x6c, 0xd2,
	0x85, 0x23, 0x38, 0x83, 0x81, 0x7b, 0x39, 0xca, 0x55, 0x36, 0xd3, 0x86, 0x29, 0x73, 0x2f, 0x59,
	0xe4, 0x5d, 0xda, 0x86, 0x29, 0x56, 0xa7, 0xd9, 0x64, 0xc2, 0x95, 0xb2, 0xa2, 0x75, 0xe9, 0xc2,
	0x61, 0xea, 0x98, 0x73, 0xa5, 0xd8, 0x94, 0x13, 0xcf, 0xd5, 0x91, 0x9b, 0xc1, 0x31, 0xac, 0x53,
	0x3e, 0x8d, 0x95, 0x4e, 0x99, 0x8e, 0xa5, 0xa0, 0x5c, 0x25, 0x52, 0x28, 0x5e, 0xe7, 0x43, 0xff,
	0xe0, 0x6b, 0xd4, 0xf9, 0x8e, 0x60, 0x6d, 0x3f, 0x8a, 0x8c, 0xc0, 0xff, 0x4d, 0xf5, 0xbb, 0x01,
	0x9d, 0xd3, 0x6c, 0xfe, 0x9e, 0x69, 0x86, 0xb7, 0xa0, 0x75, 0x36, 0x93, 0x93, 0x4b, 0x82, 0x6c,
	0x37, 0x3d, 0xca, 0xbb, 0x29, 0x3f, 0xde, 0x3c, 0x30, 0x67, 0x1f, 0x84, 0x4e, 0xaf, 0xa9, 0xc3,
	0xe1, 0x97, 0xd0, 0x8c, 0xc5, 0xb9, 0x24, 0x0d, 0x8b, 0x27, 0x37, 0xf0, 0x66, 0x14, 0x1c, 0xdc,
	0xa2, 0x0c, 0xfa, 0x42, 0xca, 0x4b, 0xe2, 0x2d, 0x45, 0x1f, 0x4a, 0x99, 0x93, 0x5b, 0x94, 0x49,
	0x39, 0xe5, 0xdf, 0x33, 0xae, 0x34, 0x69, 0x8e, 0x50, 0xe8, 0xd1, 0xc2, 0xf4, 0x77, 0x01, 0x16,
	0xa9, 0x14, 0x2d, 0x8c, 0x16, 0x2d, 0xbc, 0x0e, 0xad, 0x2b, 0x36, 0xcb, 0x5c, 0xa9, 0x1e, 0x75,
	0xc6, 0x5e, 0x63, 0x17, 0xf9, 0x3b, 0xd0, 0x2b, 0x93, 0xba, 0x6b, 0x60, 0x99, 0xdf, 0x5d, 0x02,
	0x83, 0x3f, 0x08, 0x56, 0x0f, 0x39, 0x4b, 0xf5, 0x01, 0x67, 0xba, 0xb2, 0x1b, 0xbc, 0x72, 0x22,
	0xde, 0x40, 0x47, 0x39, 0x09, 0x72, 0xd9, 0x9f, 0xe6, 0xc2, 0xd4, 0xc2, 0x0a, 0x99, 0x9c, 0x42,
	0x45, 0x04, 0xde, 0x81, 0x41, 0x56, 0x69, 0xde, 0x7c, 0x7d, 0x3c, 0xc8, 0x19, 0xaa, 0x7d, 0x4d,
	0x6b, 0x40, 0xff, 0x23, 0x0c, 0xaa, 0x8c, 0x4b, 0x6a, 0x7a, 0x56, 0xad, 0xa9, 0x3f, 0x1e, 0xd6,
	0x9f, 0xab, 0x5a, 0xe3, 0x6b, 0x68, 0xbb, 0x85, 0x63, 0xa6, 0x5b, 0x98, 0xc5, 0xe1, 0x68, 0xec,
	0xbf, 0x79, 0xc7, 0x89, 0x14, 0x9a, 0x0b, 0x97, 0xdd, 0x80, 0x16, 0x66, 0xf0, 0x02, 0x86, 0xf5,
	0x05, 0x57, 0xc5, 0xa2, 0x1a, 0x76, 0xfc, 0x0b, 0x41, 0xf7, 0x53, 0xc2, 0x05, 0xdd, 0x3f, 0x3d,
	0xc1, 0x7b, 0xd0, 0x2b, 0xc5, 0xc1, 0xeb, 0xcb, 0xe4, 0xf2, 0xef, 0xd7, 0x24, 0x30, 0xae, 0x60,
	0x25, 0x44, 0xdb, 0x08, 0xef, 0x40, 0xd7, 0x8d, 0x22, 0x4f, 0xf1, 0x20, 0x07, 0xd9, 0xdd, 0xe8,
	0x3f, 0xce, 0xad, 0x65, 0x93, 0x1a, 0xac, 0xe0, 0x6d, 0xe8, 0xe4, 0x33, 0x87, 0xfb, 0x05, 0x92,
	0xa9, 0xc4, 0xdf, 0x28, 0x48, 0xea, 0x03, 0x19, 0xac, 0x9c, 0xb5, 0xed, 0xc1, 0xab, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xbf, 0x9e, 0x14, 0xfd, 0x40, 0x06, 0x00, 0x00,
}
